kind: "AppStack"
apiVersion: "v1"

# Configuración de ejecución para el contenedor de Next.js
runConfig:
  region: "us-central1"
  cpu: 1
  memoryMiB: 512

# Usamos variables de entorno planas tal como las configuraste en la consola
# Al no usar la palabra 'secret', App Hosting buscará valores normales.
env:
  - variable: GENAI_API_KEY
  - variable: ADMIN_SERVICE_ACCOUNT
  - variable: APP_BASE_URL
